[build-system]
requires = ["maturin>=1.2,<2.0"]
build-backend = "maturin"

[project]
name = "powerboxes"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
license = "MIT"


[tool.maturin]
python-source = "python"
module-name = "powerboxes.powerboxesrs"
bindings = "pyo3"
features = ["pyo3/extension-module"]
